var textos_EN = {
    'text_titulo_app': 'ET2 UI Interface',
    'text_titulo_menu': 'Menu options',
    'label_seleccioncolumnas': 'Select columns',
    'RECORDSET_VACIO': 'No matches found',

    'menu_alumnograduacion': 'Graduation students',
    'menu_articulo': 'Scientific articles',
    'menu_ubicacion': 'Site locations',

    'text_titulo_page_alumnograduacion': 'Graduation students management',
    'text_contenido_titulo_form_alumnograduacion_ADD': 'Create graduation student',
    'text_contenido_titulo_form_alumnograduacion_EDIT': 'Update graduation student',
    'text_contenido_titulo_form_alumnograduacion_DELETE': 'Delete graduation student',
    'text_contenido_titulo_form_alumnograduacion_SHOWCURRENT': 'Graduation student detail',
    'text_contenido_titulo_form_alumnograduacion_SEARCH': 'Search graduation students',

    'label_alumnograduacion_login': 'Username',
    'label_alumnograduacion_password': 'Password',
    'label_alumnograduacion_nombre': 'First name',
    'label_alumnograduacion_apellidos': 'Surname(s)',
    'label_alumnograduacion_titulacion': 'Degree',
    'label_alumnograduacion_dni': 'National ID',
    'label_alumnograduacion_telefono': 'Phone number',
    'label_alumnograduacion_direccion': 'Postal address',
    'label_alumnograduacion_email': 'Email address',
    'label_alumnograduacion_fotoacto': 'Ceremony photo',
    'label_nuevo_alumnograduacion_fotoacto': 'Ceremony photo (upload)',

    'alumnograduacion_login_min_size_KO': 'The username must contain at least 3 characters.',
    'alumnograduacion_login_max_size_KO': 'The username cannot exceed 20 characters.',
    'alumnograduacion_login_format_KO': 'The username only allows letters, digits and underscores.',
    'alumnograduacion_password_min_size_KO': 'The password must contain at least 8 characters.',
    'alumnograduacion_password_max_size_KO': 'The password cannot exceed 30 characters.',
    'alumnograduacion_password_format_KO': 'The password only allows letters, digits, dots, hyphen and underscore.',
    'alumnograduacion_nombre_min_size_KO': 'The first name must contain at least 3 characters.',
    'alumnograduacion_nombre_max_size_KO': 'The first name cannot exceed 40 characters.',
    'alumnograduacion_nombre_format_KO': 'The first name only allows letters and spaces.',
    'alumnograduacion_apellidos_min_size_KO': 'The surnames must contain at least 3 characters.',
    'alumnograduacion_apellidos_max_size_KO': 'The surnames cannot exceed 60 characters.',
    'alumnograduacion_apellidos_format_KO': 'The surnames only allow letters and spaces.',
    'alumnograduacion_titulacion_min_size_KO': 'The degree must contain at least 2 characters.',
    'alumnograduacion_titulacion_max_size_KO': 'The degree cannot exceed 10 characters.',
    'alumnograduacion_titulacion_format_KO': 'The degree may only contain capital letters.',
    'alumnograduacion_dni_format_KO': 'The national ID must contain 8 digits followed by an uppercase letter.',
    'alumnograduacion_dni_letter_KO': 'The control letter of the national ID is not valid.',
    'alumnograduacion_telefono_format_KO': 'The phone number must contain 9 digits.',
    'alumnograduacion_direccion_min_size_KO': 'The address must contain at least 5 characters.',
    'alumnograduacion_direccion_max_size_KO': 'The address cannot exceed 120 characters.',
    'alumnograduacion_direccion_format_KO': 'The address only allows letters, digits, spaces and basic punctuation.',
    'alumnograduacion_email_format_KO': 'The email address has an invalid format.',
    'alumnograduacion_fotoacto_format_name_file_KO': 'The file name only allows letters, digits, dots, hyphen and underscore.',
    'nuevo_alumnograduacion_fotoacto_not_exist_file_KO': 'The ceremony photo is required.',
    'nuevo_alumnograduacion_fotoacto_type_file_KO': 'The ceremony photo must be JPG, PNG or GIF.',
    'nuevo_alumnograduacion_fotoacto_max_size_file_KO': 'The ceremony photo exceeds the allowed size (5MB).',
    'nuevo_alumnograduacion_fotoacto_format_name_file_KO': 'The file name only allows letters, digits, dots, hyphen and underscore.',

    'text_titulo_page_articulo': 'Scientific articles management',
    'text_contenido_titulo_form_articulo_ADD': 'Create article',
    'text_contenido_titulo_form_articulo_EDIT': 'Update article',
    'text_contenido_titulo_form_articulo_DELETE': 'Delete article',
    'text_contenido_titulo_form_articulo_SHOWCURRENT': 'Article detail',
    'text_contenido_titulo_form_articulo_SEARCH': 'Search articles',

    'label_CodigoA': 'Article code',
    'label_AutoresA': 'Authors',
    'label_TituloA': 'Article title',
    'label_TituloR': 'Journal title',
    'label_ISSN': 'ISSN',
    'label_VolumenR': 'Volume',
    'label_PagIniA': 'First page',
    'label_PagFinA': 'Last page',
    'label_FechaPublicacionR': 'Publication date',
    'label_FicheropdfA': 'PDF file',
    'label_nuevo_FicheropdfA': 'Upload PDF',
    'label_EstadoA': 'Process status',

    'CodigoA_min_size_KO': 'The article code is required.',
    'CodigoA_format_KO': 'The article code only allows digits.',
    'AutoresA_min_size_KO': 'At least one author must be provided.',
    'AutoresA_max_size_KO': 'Authors cannot exceed 200 characters.',
    'AutoresA_format_KO': 'Authors only allow letters, spaces, commas and dots.',
    'TituloA_min_size_KO': 'The article title is required.',
    'TituloA_max_size_KO': 'The article title cannot exceed 100 characters.',
    'TituloA_format_KO': 'The article title contains invalid characters.',
    'TituloR_min_size_KO': 'The journal title is required.',
    'TituloR_max_size_KO': 'The journal title cannot exceed 100 characters.',
    'TituloR_format_KO': 'The journal title contains invalid characters.',
    'ISSN_min_size_KO': 'The ISSN must contain 9 characters.',
    'ISSN_format_KO': 'The ISSN must follow the 0000-000X format.',
    'VolumenR_min_size_KO': 'The journal volume is required.',
    'VolumenR_format_KO': 'The volume only allows up to four digits.',
    'PagIniA_min_size_KO': 'The first page is required.',
    'PagIniA_format_KO': 'The first page only allows digits.',
    'PagFinA_min_size_KO': 'The last page is required.',
    'PagFinA_format_KO': 'The last page only allows digits.',
    'PagFinA_range_KO': 'The last page must be equal or greater than the first page.',
    'FechaPublicacionR_format_KO': 'The date must follow the dd/mm/yyyy format.',
    'FechaPublicacionR_value_KO': 'The provided date is not valid.',
    'EstadoA_value_KO': 'Select a valid status.',
    'nuevo_FicheropdfA_not_exist_file_KO': 'The article PDF is required.',
    'nuevo_FicheropdfA_type_file_KO': 'The article file must be a PDF.',
    'nuevo_FicheropdfA_max_size_file_KO': 'The article file exceeds the 5MB limit.',
    'nuevo_FicheropdfA_format_name_file_KO': 'The article file name only allows letters, digits, hyphen and dot.',

    'text_titulo_page_ubicacion': 'Sites management',
    'text_contenido_titulo_form_ubicacion_ADD': 'Create site',
    'text_contenido_titulo_form_ubicacion_EDIT': 'Update site',
    'text_contenido_titulo_form_ubicacion_DELETE': 'Delete site',
    'text_contenido_titulo_form_ubicacion_SHOWCURRENT': 'Site detail',
    'text_contenido_titulo_form_ubicacion_SEARCH': 'Search sites',

    'label_id_site': 'Identifier',
    'label_site_latitud': 'Latitude (WGS84)',
    'label_site_longitud': 'Longitude (WGS84)',
    'label_site_altitude': 'Altitude (m)',
    'label_site_locality': 'Locality',
    'label_site_provider_login': 'Provider login',
    'label_site_north_photo': 'North photo',
    'label_site_south_photo': 'South photo',
    'label_site_east_photo': 'East photo',
    'label_site_west_photo': 'West photo',
    'label_nuevo_site_north_photo': 'Upload north photo',
    'label_nuevo_site_south_photo': 'Upload south photo',
    'label_nuevo_site_east_photo': 'Upload east photo',
    'label_nuevo_site_west_photo': 'Upload west photo',

    'id_site_format_KO': 'The identifier must be numeric.',
    'site_latitud_format_KO': 'Latitude must be a decimal number with up to six decimals.',
    'site_latitud_range_KO': 'Latitude must be between -90 and 90 degrees.',
    'site_longitud_format_KO': 'Longitude must be a decimal number with up to six decimals.',
    'site_longitud_range_KO': 'Longitude must be between -180 and 180 degrees.',
    'site_altitude_format_KO': 'Altitude must be an integer number.',
    'site_altitude_range_KO': 'Altitude must be between -500 and 9000 metres.',
    'site_locality_min_size_KO': 'The locality must contain at least 3 characters.',
    'site_locality_max_size_KO': 'The locality cannot exceed 40 characters.',
    'site_locality_format_KO': 'The locality only allows letters, spaces and hyphen.',
    'site_provider_login_min_size_KO': 'The login must contain at least 3 characters.',
    'site_provider_login_max_size_KO': 'The login cannot exceed 30 characters.',
    'site_provider_login_format_KO': 'The login only allows letters, digits, hyphen and underscore.',
    'nuevo_site_north_photo_not_exist_file_KO': 'North photo is required.',
    'nuevo_site_north_photo_type_file_KO': 'North photo must be JPG or PNG.',
    'nuevo_site_north_photo_max_size_file_KO': 'North photo exceeds the 5MB limit.',
    'nuevo_site_north_photo_format_name_file_KO': 'North photo name only allows letters, digits, hyphen and dot.',
    'nuevo_site_south_photo_not_exist_file_KO': 'South photo is required.',
    'nuevo_site_south_photo_type_file_KO': 'South photo must be JPG or PNG.',
    'nuevo_site_south_photo_max_size_file_KO': 'South photo exceeds the 5MB limit.',
    'nuevo_site_south_photo_format_name_file_KO': 'South photo name only allows letters, digits, hyphen and dot.',
    'nuevo_site_east_photo_not_exist_file_KO': 'East photo is required.',
    'nuevo_site_east_photo_type_file_KO': 'East photo must be JPG or PNG.',
    'nuevo_site_east_photo_max_size_file_KO': 'East photo exceeds the 5MB limit.',
    'nuevo_site_east_photo_format_name_file_KO': 'East photo name only allows letters, digits, hyphen and dot.',
    'nuevo_site_west_photo_not_exist_file_KO': 'West photo is required.',
    'nuevo_site_west_photo_type_file_KO': 'West photo must be JPG or PNG.',
    'nuevo_site_west_photo_max_size_file_KO': 'West photo exceeds the 5MB limit.',
    'nuevo_site_west_photo_format_name_file_KO': 'West photo name only allows letters, digits, hyphen and dot.'
};
